version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auditly_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://auditly_user:secret_pass@db:5432/auditly_db
    depends_on:
      - db


  db:
    image: postgres:15-alpine
    container_name: auditly_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=auditly_user
      - POSTGRES_PASSWORD=secret_pass
      - POSTGRES_DB=auditly_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
